const {test}=require('node:test');
const assert=require('node:assert/strict');
const m=require('../motion/browser/motion.js');
const base=require('../motion/examples/keyphrase.json');
const spec=()=>structuredClone(base);
test('valid spec',()=>assert.equal(m.validate(spec()).template,'keyphrase'));
test('frame determinism including out-of-order access',()=>{const s=spec();const a=m.renderFrame(45,s);m.renderFrame(89,s);m.renderFrame(0,s);assert.equal(a,m.renderFrame(45,s));});
test('animation starts and ends transparent',()=>{const s=spec();assert.equal(m.state(0,s).opacity,0);assert.equal(m.state(s.duration_frames-1,s).opacity,0);});
test('middle frame is visible',()=>assert.equal(m.state(45,spec()).opacity,1));
test('outside range is invisible',()=>{assert.equal(m.state(-1,spec()).opacity,0);assert.equal(m.state(90,spec()).opacity,0)});
test('different valid frames produce motion',()=>assert.notEqual(m.renderFrame(1,spec()),m.renderFrame(4,spec())));
test('string injection is escaped',()=>{const s=spec();s.lines=['<script>alert(1)</script>'];const svg=m.renderFrame(30,s);assert.ok(svg.includes('&lt;script&gt;'));assert.ok(!svg.includes('<script>'));});
test('reject non-finite fps',()=>{const s=spec();s.fps=NaN;assert.throws(()=>m.validate(s));});
test('reject fractional frame count',()=>{const s=spec();s.duration_frames=2.4;assert.throws(()=>m.validate(s));});
test('reject fractional frame index',()=>assert.throws(()=>m.renderFrame(1.5,spec())));
test('reject missing child scope',()=>{const s=spec();s.child_id='';assert.throws(()=>m.validate(s));});
test('reject unknown template',()=>{const s=spec();s.template='untrusted.js';assert.throws(()=>m.validate(s));});
test('reject invalid style injection',()=>{const s=spec();s.colors.accent='url(https://bad/)';assert.throws(()=>m.validate(s));});
test('reject off-canvas box',()=>{const s=spec();s.box.x=.9;assert.throws(()=>m.validate(s));});
test('reject remote image',()=>{const s=spec();s.asset_data_uri='https://example.com/a.png';assert.throws(()=>m.validate(s));});
test('reject SVG image payload',()=>{const s=spec();s.asset_data_uri='data:image/svg+xml;base64,AAAA';assert.throws(()=>m.validate(s));});
test('proof requires actual image',()=>{const s=spec();s.template='proof-frame';assert.throws(()=>m.renderFrame(10,s));});
test('steps are not generic text-only effect',()=>{const s=require('../motion/examples/steps.json');const f=m.renderFrame(45,s);assert.ok(f.includes('Gravar a ideia'));assert.ok(f.includes('03'));});
test('template does not mutate caller props',()=>{const s=spec();const before=JSON.stringify(s);m.renderFrame(15,s);assert.equal(JSON.stringify(s),before);});
test('long text fails instead of clipping silently',()=>{const s=spec();s.lines=['a'.repeat(70)];assert.throws(()=>m.validate(s));});
